<?php

/** Per-service rich copy — used on hub previews and detail pages. */
const TS_SERVICE_PAGES = [
    "search-engine-optimization" => [
        "lead" => "Rank higher on Google with technical SEO, keyword strategy and content that brings qualified organic traffic to your site.",
        "overview" => "Our SEO team audits your site architecture, fixes crawl issues and builds a keyword roadmap aligned to buyer intent. We optimize on-page elements, improve Core Web Vitals and earn authoritative backlinks so your brand becomes visible where customers search.",
        "features" => [
            ["Technical SEO Audit", "Crawl analysis, indexation fixes, schema markup and site speed improvements."],
            ["Keyword & Content Strategy", "Topic clusters, search intent mapping and editorial calendars."],
            ["On-Page Optimization", "Title tags, meta descriptions, internal linking and content refreshes."],
            ["Link Building & Reporting", "Ethical outreach, digital PR and monthly rank/traffic dashboards."],
        ],
        "benefits" => [
            ["Sustainable Traffic", "Organic visitors that compound over time without paying per click."],
            ["Higher Intent Leads", "Rank for queries from people actively looking for your solution."],
            ["Brand Authority", "Top positions signal trust and expertise in your industry."],
            ["Measurable ROI", "Track rankings, clicks and conversions tied to revenue."],
        ],
        "use_cases" => ["Local businesses targeting city-level searches", "SaaS companies competing for product keywords", "E-commerce stores scaling product and category pages"],
        "technologies" => ["Google Search Console", "GA4", "SEMrush", "Ahrefs", "Screaming Frog", "Schema.org"],
    ],
    "search-engine-marketing" => [
        "lead" => "Capture demand instantly with Google Ads and Bing campaigns optimized for clicks, conversions and cost efficiency.",
        "overview" => "We structure search campaigns around high-intent keywords, write compelling ad copy and build landing pages that convert. Conversion tracking, remarketing lists and bid strategies are tuned weekly so your budget works harder.",
        "features" => [
            ["Campaign Architecture", "Brand, competitor and generic keyword tiers with smart bidding."],
            ["Ad Copy & Extensions", "Responsive search ads, sitelinks and callouts tested for CTR."],
            ["Landing Page Alignment", "Message match between ads and pages to lift Quality Score."],
            ["Performance Optimization", "Search term mining, negative keywords and budget reallocation."],
        ],
        "benefits" => [
            ["Immediate Visibility", "Appear at the top of results while SEO gains momentum."],
            ["Full Funnel Control", "Target awareness, consideration and purchase stages separately."],
            ["Transparent Metrics", "Cost per lead, ROAS and conversion paths in clear reports."],
            ["Scalable Spend", "Increase budget on winning campaigns with confidence."],
        ],
        "use_cases" => ["Product launches needing instant traffic", "B2B lead generation with form fills", "Seasonal promotions with time-bound offers"],
        "technologies" => ["Google Ads", "Microsoft Ads", "Google Tag Manager", "GA4", "Looker Studio"],
    ],
    "social-media-marketing" => [
        "lead" => "Build community, engagement and leads across Instagram, LinkedIn, Facebook and emerging platforms.",
        "overview" => "We craft platform-native content calendars, design scroll-stopping creatives and manage communities that reflect your brand voice. Paid social amplifies top organic posts while analytics show what drives followers, clicks and sales.",
        "features" => [
            ["Content Strategy", "Pillar topics, posting cadence and platform-specific formats."],
            ["Creative Production", "Reels, carousels, stories and ad creatives on brand."],
            ["Community Management", "Replies, DMs and reputation monitoring with SLA response times."],
            ["Paid Social Campaigns", "Audience targeting, retargeting and conversion campaigns."],
        ],
        "benefits" => [
            ["Brand Awareness", "Stay top-of-mind where your audience spends time daily."],
            ["Direct Engagement", "Two-way conversations that build loyalty and trust."],
            ["Traffic & Leads", "Drive clicks to landing pages, apps and product pages."],
            ["Social Proof", "User-generated content and testimonials amplify credibility."],
        ],
        "use_cases" => ["D2C brands building Instagram communities", "B2B companies establishing LinkedIn thought leadership", "Restaurants and retail driving footfall with local campaigns"],
        "technologies" => ["Meta Business Suite", "LinkedIn Campaign Manager", "Canva", "Hootsuite", "Sprout Social"],
    ],
    "content-marketing" => [
        "lead" => "Attract and nurture customers with blogs, guides, case studies and video content that ranks and converts.",
        "overview" => "Content marketing fuels SEO, social and email channels with assets your audience actually wants. We research topics, produce SEO-optimized articles and distribute across channels — measuring engagement from first read to signed contract.",
        "features" => [
            ["Editorial Planning", "Quarterly content maps tied to funnel stages and keywords."],
            ["Long-Form Writing", "Blogs, whitepapers, ebooks and case studies by subject experts."],
            ["SEO Content Optimization", "Structure, headings, internal links and refresh cycles."],
            ["Distribution & Repurposing", "Newsletters, social snippets and sales enablement packs."],
        ],
        "benefits" => [
            ["Trust at Scale", "Educational content positions you as the go-to expert."],
            ["Lower CAC", "Organic content reduces reliance on paid acquisition."],
            ["Sales Enablement", "Assets that shorten cycles and answer buyer objections."],
            ["Evergreen Value", "Quality articles keep generating traffic for years."],
        ],
        "use_cases" => ["SaaS blogs driving demo requests", "Professional services firms publishing thought leadership", "E-commerce content hubs supporting product discovery"],
        "technologies" => ["WordPress", "HubSpot CMS", "Clearscope", "Grammarly", "GA4"],
    ],
    "pay-per-click" => [
        "lead" => "Maximize return on ad spend with precision-targeted PPC across Google, Meta and display networks.",
        "overview" => "Our PPC specialists manage account structure, creative testing and landing page experiments so every dollar counts. We set up conversion tracking from day one and optimize toward your KPI — whether that's leads, purchases or app installs.",
        "features" => [
            ["Account Setup & Structure", "Campaigns, ad groups and audiences organized for clarity."],
            ["Creative Testing", "A/B ad variants, offers and CTAs refined continuously."],
            ["Bid & Budget Management", "Manual and automated bidding aligned to business goals."],
            ["ROAS Reporting", "Weekly dashboards with actionable recommendations."],
        ],
        "benefits" => [
            ["Predictable Costs", "Pay only when users click — full spend transparency."],
            ["Fast Iteration", "Test offers and messaging within days, not months."],
            ["Granular Targeting", "Reach by keyword, interest, job title or purchase behavior."],
            ["Cross-Channel Synergy", "Retarget site visitors across search and social."],
        ],
        "use_cases" => ["E-commerce stores scaling during peak seasons", "Lead-gen businesses with CPL targets", "App install campaigns on mobile networks"],
        "technologies" => ["Google Ads", "Meta Ads", "Google Analytics", "Hotjar", "Unbounce"],
    ],
    "email-campaigns" => [
        "lead" => "Turn subscribers into customers with automated email flows, newsletters and lifecycle campaigns.",
        "overview" => "Email remains one of the highest-ROI channels when done right. We design on-brand templates, segment lists by behavior and build automations for welcome series, cart recovery and re-engagement — all tracked with open, click and revenue attribution.",
        "features" => [
            ["Template Design", "Mobile-responsive emails matching your brand system."],
            ["Automation Workflows", "Triggers for signup, purchase, churn risk and upsell."],
            ["List Segmentation", "Behavioral and demographic splits for relevance."],
            ["Analytics & Testing", "Subject line A/B tests and deliverability monitoring."],
        ],
        "benefits" => [
            ["Owned Audience", "Reach customers without algorithm changes or ad costs."],
            ["Personalization", "Dynamic content based on past purchases and interests."],
            ["Revenue Recovery", "Abandoned cart and win-back flows recapture lost sales."],
            ["Nurture at Scale", "Educate prospects until they are ready to buy."],
        ],
        "use_cases" => ["E-commerce lifecycle and promotional sends", "B2B nurture sequences for long sales cycles", "Event and webinar registration follow-ups"],
        "technologies" => ["Mailchimp", "HubSpot", "Klaviyo", "SendGrid", "Litmus"],
    ],
    "analytics-and-reporting" => [
        "lead" => "Make data-driven decisions with GA4, custom dashboards and KPI frameworks tailored to your business.",
        "overview" => "If you cannot measure it, you cannot improve it. We implement tracking correctly, build executive dashboards and translate metrics into clear recommendations — so marketing, product and leadership align on what is working.",
        "features" => [
            ["Tracking Setup", "GA4, GTM, event taxonomy and e-commerce measurement."],
            ["Custom Dashboards", "Looker Studio or Power BI views for each stakeholder."],
            ["KPI Framework", "North-star metrics, targets and reporting cadence."],
            ["Insight Reports", "Monthly narratives with trends, anomalies and next steps."],
        ],
        "benefits" => [
            ["Single Source of Truth", "One dashboard everyone trusts for performance."],
            ["Faster Decisions", "Spot issues and opportunities without digging through tools."],
            ["Attribution Clarity", "Understand which channels drive revenue."],
            ["Compliance Ready", "Consent mode and privacy-conscious tracking setup."],
        ],
        "use_cases" => ["Marketing teams needing unified campaign reporting", "E-commerce stores tracking funnel drop-offs", "Startups defining metrics for investors"],
        "technologies" => ["GA4", "Google Tag Manager", "Looker Studio", "BigQuery", "Hotjar"],
    ],
    "website-development" => [
        "lead" => "Launch fast, responsive websites and web apps with modern stacks, SEO-ready structure and easy content management.",
        "overview" => "From marketing sites to customer portals, we build performant web experiences on WordPress, Laravel or headless architectures. Every project includes mobile-first design, accessibility basics, analytics setup and training so your team can update content confidently.",
        "features" => [
            ["UX & Information Architecture", "Sitemaps, wireframes and conversion-focused layouts."],
            ["Frontend Development", "Responsive HTML/CSS/JS or React/Next.js interfaces."],
            ["CMS & Admin", "WordPress, custom admin or headless CMS integration."],
            ["Launch & Handover", "Hosting setup, SSL, SEO basics and editor training."],
        ],
        "benefits" => [
            ["Professional First Impression", "Design and speed that build instant credibility."],
            ["Search-Ready Foundation", "Clean URLs, meta tags and structured data from launch."],
            ["Easy Updates", "CMS workflows so marketing is not blocked by dev tickets."],
            ["Secure & Maintainable", "Updates, backups and monitoring options post-launch."],
        ],
        "use_cases" => ["Corporate marketing and brochure sites", "Startup landing pages for product launches", "Member portals and customer dashboards"],
        "technologies" => ["React", "Next.js", "WordPress", "Laravel", "Tailwind CSS", "Vercel"],
    ],
    "software-development" => [
        "lead" => "Custom software tailored to your workflows — from internal tools to customer-facing SaaS platforms.",
        "overview" => "We partner with you from discovery through deployment, building applications with clean architecture, automated tests and documentation your team can extend. Agile sprints, transparent demos and DevOps practices keep delivery predictable.",
        "features" => [
            ["Requirements & Discovery", "Workshops, user stories and technical specifications."],
            ["Architecture & APIs", "Scalable backend design with REST or GraphQL interfaces."],
            ["Agile Development", "Two-week sprints, code reviews and CI/CD pipelines."],
            ["QA & Documentation", "Automated tests, staging environments and runbooks."],
        ],
        "benefits" => [
            ["Process Fit", "Software shaped around how your team actually works."],
            ["Competitive Edge", "Features competitors cannot buy off the shelf."],
            ["Integration Ready", "Connect CRM, ERP, payment and third-party tools."],
            ["Long-Term Ownership", "You own the codebase with no vendor lock-in."],
        ],
        "use_cases" => ["Internal ops and workflow automation tools", "B2B SaaS products entering the market", "Legacy system modernization projects"],
        "technologies" => ["Node.js", "Laravel", "Python", "PostgreSQL", "Docker", "AWS"],
    ],
    "crm-software" => [
        "lead" => "Implement and customize CRM platforms so sales, marketing and support share one view of the customer.",
        "overview" => "Whether HubSpot, Salesforce or a custom build, we configure pipelines, automations and reports that match your sales process. Data migration, team training and integrations ensure adoption — not another shelfware tool.",
        "features" => [
            ["CRM Selection & Setup", "Platform choice, instance configuration and permissions."],
            ["Pipeline Automation", "Stages, tasks, email sequences and lead scoring."],
            ["Integrations", "Website forms, email, telephony and accounting sync."],
            ["Reporting Dashboards", "Forecasting, activity metrics and revenue views."],
        ],
        "benefits" => [
            ["Unified Customer Data", "Every touchpoint logged in one place."],
            ["Shorter Sales Cycles", "Automated follow-ups so leads never go cold."],
            ["Forecast Accuracy", "Pipeline visibility for leadership planning."],
            ["Marketing Alignment", "Handoff rules between MQL and SQL stages."],
        ],
        "use_cases" => ["Sales teams outgrowing spreadsheets", "Marketing automation tied to CRM records", "Support tickets linked to account history"],
        "technologies" => ["HubSpot", "Salesforce", "Zoho CRM", "Pipedrive", "Zapier"],
    ],
    "sharepoint-integration" => [
        "lead" => "Organize documents, workflows and collaboration with SharePoint tailored to your Microsoft 365 environment.",
        "overview" => "We design information architecture, permission models and automated workflows so teams find files fast and stay compliant. Integrations with Teams, Power Automate and line-of-business apps reduce duplicate work.",
        "features" => [
            ["Site Architecture", "Hub sites, libraries and metadata taxonomy."],
            ["Workflow Automation", "Approval flows, notifications and Power Automate."],
            ["Permissions & Governance", "Role-based access and retention policies."],
            ["Training & Adoption", "Documentation and sessions for end users."],
        ],
        "benefits" => [
            ["Centralized Documents", "Single version of truth across departments."],
            ["Compliance", "Audit trails and controlled access for sensitive data."],
            ["Productivity", "Less time searching email attachments for files."],
            ["Microsoft Ecosystem", "Works seamlessly with Teams, Outlook and Office."],
        ],
        "use_cases" => ["Enterprise document management", "HR and policy portal hosting", "Project collaboration extranets"],
        "technologies" => ["SharePoint Online", "Microsoft 365", "Power Automate", "Azure AD", "Graph API"],
    ],
    "netsuite-integration" => [
        "lead" => "Connect NetSuite to your stack — ecommerce, CRM, warehousing and custom apps with reliable sync.",
        "overview" => "NetSuite is powerful when integrated correctly. We customize records, build SuiteScript automations and connect third-party systems via REST or middleware so orders, inventory and financials stay accurate in real time.",
        "features" => [
            ["NetSuite Customization", "Fields, forms, workflows and saved searches."],
            ["Third-Party Connectors", "Shopify, Amazon, Salesforce and custom APIs."],
            ["Data Migration", "Clean imports with validation and reconciliation."],
            ["Process Automation", "Order-to-cash and procure-to-pay workflows."],
        ],
        "benefits" => [
            ["Operational Efficiency", "Eliminate manual re-entry between systems."],
            ["Real-Time Inventory", "Stock levels accurate across channels."],
            ["Financial Accuracy", "Revenue recognition and reporting you can trust."],
            ["Scalable Operations", "Handle growth without adding headcount."],
        ],
        "use_cases" => ["Multi-channel retailers syncing orders", "Manufacturers connecting ERP to shop floor", "Wholesale B2B portals with NetSuite backend"],
        "technologies" => ["NetSuite", "SuiteScript", "REST APIs", "Celigo", "Boomi"],
    ],
    "e-commerce-platforms" => [
        "lead" => "Launch and grow online stores on Shopify, WooCommerce or custom platforms built for conversion.",
        "overview" => "We handle storefront design, payment gateways, inventory sync and checkout optimization. From catalog setup to abandoned cart flows, every detail is tuned to reduce friction and increase average order value.",
        "features" => [
            ["Store Design & UX", "Product pages, collections and mobile checkout."],
            ["Payment & Shipping", "Gateways, tax rules and carrier integrations."],
            ["Inventory & Orders", "SKU management, fulfillment workflows and notifications."],
            ["Conversion Optimization", "Upsells, reviews, speed and analytics tracking."],
        ],
        "benefits" => [
            ["Revenue Growth", "Stores engineered to convert browsers into buyers."],
            ["Omnichannel Ready", "Sync with marketplaces and POS where needed."],
            ["Marketing Integrations", "Pixels, feeds and email tools connected day one."],
            ["Secure Transactions", "PCI-aware checkout and fraud considerations."],
        ],
        "use_cases" => ["D2C brands launching first online store", "Retailers migrating from legacy platforms", "B2B wholesale ordering portals"],
        "technologies" => ["Shopify", "WooCommerce", "Stripe", "Magento", "React"],
    ],
    "api-and-cloud-apps" => [
        "lead" => "Build secure REST and GraphQL APIs plus cloud-native apps on AWS, Azure or GCP.",
        "overview" => "APIs are the backbone of modern products. We design contracts, implement authentication, deploy to cloud infrastructure and document endpoints so partners and internal teams integrate quickly and safely.",
        "features" => [
            ["API Design", "RESTful or GraphQL schemas with versioning strategy."],
            ["Auth & Security", "OAuth, JWT, rate limiting and input validation."],
            ["Cloud Deployment", "Containers, serverless or managed services with monitoring."],
            ["Developer Docs", "OpenAPI specs, SDKs and sandbox environments."],
        ],
        "benefits" => [
            ["Integration Speed", "Partners connect in days with clear documentation."],
            ["Scalability", "Auto-scaling infrastructure handles traffic spikes."],
            ["Reliability", "Health checks, logging and alerting built in."],
            ["Future-Proof", "Modular services easy to extend and replace."],
        ],
        "use_cases" => ["Mobile apps needing backend APIs", "Partner ecosystems and marketplaces", "Microservices modernization"],
        "technologies" => ["Node.js", "Laravel", "AWS Lambda", "Docker", "Kubernetes", "Postman"],
    ],
    "android-app-development" => [
        "lead" => "Native Android apps with Material Design, smooth performance and Play Store-ready delivery.",
        "overview" => "We build Android applications in Kotlin with modern architecture components, offline support and secure API integration. From MVPs to enterprise apps, our process covers design, development, testing and Play Store submission.",
        "features" => [
            ["Native Kotlin Development", "Jetpack Compose or XML layouts with best practices."],
            ["Material Design UI", "Accessible, responsive interfaces for all screen sizes."],
            ["Backend Integration", "REST/GraphQL APIs, push notifications and analytics."],
            ["Play Store Launch", "Listing assets, compliance and staged rollouts."],
        ],
        "benefits" => [
            ["Platform Performance", "Native speed and access to device features."],
            ["Google Play Reach", "Billions of Android users worldwide."],
            ["Offline Capability", "Core features work without constant connectivity."],
            ["Ongoing Updates", "Maintenance plans for OS and security patches."],
        ],
        "use_cases" => ["Consumer lifestyle and utility apps", "Field service and logistics tools", "Fintech apps with secure transactions"],
        "technologies" => ["Kotlin", "Jetpack Compose", "Firebase", "Retrofit", "Room DB"],
    ],
    "ios-app-development" => [
        "lead" => "Polished iOS apps with Swift, Human Interface Guidelines and seamless App Store deployment.",
        "overview" => "Our iOS team delivers apps that feel at home on iPhone and iPad — intuitive navigation, Face ID integration and App Store optimization included. TestFlight betas gather feedback before public launch.",
        "features" => [
            ["Swift & SwiftUI", "Modern Apple frameworks for maintainable code."],
            ["HIG-Compliant UX", "Navigation patterns users already understand."],
            ["Secure APIs", "Keychain storage, certificate pinning where required."],
            ["App Store Submission", "Review guidelines, screenshots and ASO basics."],
        ],
        "benefits" => [
            ["Premium User Base", "Reach customers with higher engagement rates."],
            ["Ecosystem Integration", "Apple Pay, widgets and Siri shortcuts."],
            ["Brand Prestige", "Quality iOS apps signal product maturity."],
            ["Regular Updates", "Compatibility with new iOS releases."],
        ],
        "use_cases" => ["Premium consumer and lifestyle apps", "Healthcare apps with privacy requirements", "Enterprise employee tools on company devices"],
        "technologies" => ["Swift", "SwiftUI", "Xcode", "TestFlight", "Firebase"],
    ],
    "react-native-apps" => [
        "lead" => "One codebase for iOS and Android — React Native apps with near-native performance and faster time to market.",
        "overview" => "React Native lets you ship to both stores simultaneously while sharing business logic. We structure projects for maintainability, use native modules where needed and optimize startup time and animations.",
        "features" => [
            ["Cross-Platform Architecture", "Shared JS layer with platform-specific tweaks."],
            ["Native Module Bridges", "Camera, biometrics and payments when required."],
            ["State & Navigation", "Redux, Zustand or Context with React Navigation."],
            ["Store Deployment", "Build pipelines for both App Store and Play Store."],
        ],
        "benefits" => [
            ["Faster Launch", "Single team delivers both platforms."],
            ["Cost Efficiency", "Lower maintenance than two native codebases."],
            ["Hot Updates", "OTA fixes for JS layer between store releases."],
            ["Large Talent Pool", "React developers easy to onboard."],
        ],
        "use_cases" => ["Startups validating product on both stores", "Internal apps with tight budgets", "Apps with frequent feature releases"],
        "technologies" => ["React Native", "Expo", "TypeScript", "Redux", "Fastlane"],
    ],
    "flutter-apps" => [
        "lead" => "Beautiful cross-platform apps with Flutter — custom widgets, smooth animations and single codebase efficiency.",
        "overview" => "Flutter's rendering engine delivers consistent UI across devices. We build performant apps with clean architecture, platform channels for native features and CI/CD for automated store builds.",
        "features" => [
            ["Custom Widgets", "Brand-unique components and design systems in Dart."],
            ["Platform Channels", "Native code integration for specialized hardware."],
            ["State Management", "Bloc, Riverpod or Provider patterns."],
            ["Performance Tuning", "Profile builds, reduce jank and optimize assets."],
        ],
        "benefits" => [
            ["Pixel-Perfect UI", "Same look on iOS, Android and web targets."],
            ["Fast Iteration", "Hot reload speeds design-dev collaboration."],
            ["Growing Ecosystem", "Google-backed with strong package library."],
            ["Web & Desktop Option", "Extend to additional platforms later."],
        ],
        "use_cases" => ["Apps needing rich custom UI and animations", "MVPs targeting multiple platforms quickly", "Enterprise apps with offline-first requirements"],
        "technologies" => ["Flutter", "Dart", "Firebase", "Bloc", "Codemagic"],
    ],
    "progressive-web-apps" => [
        "lead" => "Installable web apps with offline support, push notifications and app-like experience without store friction.",
        "overview" => "PWAs bridge web and mobile — users add to home screen, receive push alerts and browse offline. We optimize service workers, caching strategies and Lighthouse scores for performance that rivals native.",
        "features" => [
            ["Service Worker Setup", "Caching, background sync and update prompts."],
            ["Install Prompts", "Add-to-home-screen flows on supported browsers."],
            ["Push Notifications", "Re-engage users with timely alerts."],
            ["Performance Audit", "Lighthouse optimization for speed and PWA criteria."],
        ],
        "benefits" => [
            ["No Store Approval", "Deploy updates instantly without review delays."],
            ["Lower Development Cost", "One web codebase vs native dual track."],
            ["Discoverable", "Still indexable by search engines unlike native-only."],
            ["Works Offline", "Critical flows available without network."],
        ],
        "use_cases" => ["Retail and news sites wanting app-like UX", "Emerging markets with limited storage", "Internal tools for distributed teams"],
        "technologies" => ["React", "Vue", "Workbox", "Lighthouse", "Web Push API"],
    ],
    "app-ui-engineering" => [
        "lead" => "Pixel-perfect mobile UI implementation — components, animations and design-dev handoff done right.",
        "overview" => "Great design fails without great implementation. Our UI engineers translate Figma specs into production-ready screens with micro-interactions, accessibility and performance tuned for 60fps scroll and transitions.",
        "features" => [
            ["Design System Implementation", "Reusable components matching design tokens."],
            ["Micro-Interactions", "Gestures, haptics and motion that delight users."],
            ["Cross-Platform Parity", "Consistent UI on iOS and Android from one spec."],
            ["Handoff Documentation", "Specs, redlines and component usage guides."],
        ],
        "benefits" => [
            ["Design Fidelity", "What you approved is what users see."],
            ["Faster Dev Cycles", "Component library reduces duplicate work."],
            ["Better UX Scores", "Smooth interactions improve retention."],
            ["Designer-Dev Bridge", "Fewer back-and-forth rounds on visuals."],
        ],
        "use_cases" => ["Teams with designs ready but needing implementation", "Apps undergoing UI refresh without backend rewrite", "Design system rollout across product suite"],
        "technologies" => ["Figma", "React Native", "Flutter", "Lottie", "Storybook"],
    ],
    "support-and-maintenance" => [
        "lead" => "Keep your app healthy with bug fixes, OS updates, monitoring and feature enhancements on retainer.",
        "overview" => "Launch is just the beginning. We provide SLA-backed support, crash monitoring, compatibility updates for new iOS/Android releases and a backlog pipeline for iterative improvements your users request.",
        "features" => [
            ["Bug Fixes & Patches", "Priority triage and resolution within agreed SLAs."],
            ["OS Compatibility", "Updates for new Android and iOS versions."],
            ["Performance Monitoring", "Crash analytics, ANR tracking and uptime alerts."],
            ["Feature Enhancements", "Planned sprints for user-requested improvements."],
        ],
        "benefits" => [
            ["Peace of Mind", "Experts on call when something breaks."],
            ["User Retention", "Fast fixes prevent bad reviews and churn."],
            ["Predictable Costs", "Monthly retainer vs emergency contractor rates."],
            ["Continuous Improvement", "Steady roadmap progress post-launch."],
        ],
        "use_cases" => ["Apps without in-house mobile team", "Products needing 24/7 monitoring", "Legacy apps requiring modernization sprints"],
        "technologies" => ["Firebase Crashlytics", "Sentry", "Fastlane", "GitHub Actions", "App Store Connect"],
    ],
    "ui-ux-designing" => [
        "lead" => "User-centered UI/UX design — research, wireframes and high-fidelity screens that improve conversion and satisfaction.",
        "overview" => "We start with understanding users through interviews and analytics, then map journeys and wireframes before crafting polished interfaces. Usability testing validates decisions before development begins, saving rework cost.",
        "features" => [
            ["User Research", "Interviews, surveys and heuristic evaluations."],
            ["Wireframes & Flows", "Task flows, sitemaps and low-fidelity prototypes."],
            ["High-Fidelity UI", "Visual design, design tokens and responsive layouts."],
            ["Usability Testing", "Moderated sessions and iteration based on findings."],
        ],
        "benefits" => [
            ["Higher Conversion", "Friction removed from critical user paths."],
            ["Reduced Dev Waste", "Clear specs prevent expensive rebuilds."],
            ["Accessibility", "Inclusive design for broader audience reach."],
            ["Brand Consistency", "Cohesive experience across all touchpoints."],
        ],
        "use_cases" => ["SaaS products redesigning onboarding", "Mobile apps before development kickoff", "E-commerce checkout optimization"],
        "technologies" => ["Figma", "Maze", "Hotjar", "FigJam", "Principle"],
    ],
    "brand-identity" => [
        "lead" => "Define your brand with logo, color palette, typography and guidelines that scale across every channel.",
        "overview" => "Brand identity is more than a logo — it is how customers recognize and trust you. We develop strategic positioning, visual systems and comprehensive brand books so internal teams and partners stay on brand.",
        "features" => [
            ["Brand Strategy", "Positioning, voice and audience definition workshops."],
            ["Visual Identity", "Logo, color, typography and iconography systems."],
            ["Brand Guidelines", "Usage rules for print, digital and social."],
            ["Collateral Templates", "Business cards, decks and social kits."],
        ],
        "benefits" => [
            ["Memorable Presence", "Stand out in crowded markets."],
            ["Team Alignment", "Everyone creates on-brand assets consistently."],
            ["Trust Building", "Professional identity increases perceived value."],
            ["Scalable System", "Easy to extend as you launch new products."],
        ],
        "use_cases" => ["Startups launching with first brand", "Rebrands after merger or pivot", "Franchises needing local brand consistency"],
        "technologies" => ["Illustrator", "Figma", "InDesign", "Brandfolder", "Canva"],
    ],
    "logo-and-visual-design" => [
        "lead" => "Distinctive logos and visual assets for digital, print and social — delivered in every format you need.",
        "overview" => "We explore multiple logo concepts, refine based on feedback and deliver master files plus variants for dark mode, favicons and social profiles. Supporting visuals reinforce your message across campaigns.",
        "features" => [
            ["Concept Exploration", "Multiple directions with rationale for each."],
            ["Refinement Rounds", "Iterative polish until the mark feels right."],
            ["File Delivery", "SVG, PNG, EPS and source files organized."],
            ["Social & Print Kit", "Profile images, banners and stationery layouts."],
        ],
        "benefits" => [
            ["Instant Recognition", "A mark that works at any size."],
            ["Versatile Assets", "Files ready for developers and printers."],
            ["Campaign Ready", "Visuals for ads, decks and packaging."],
            ["Ownership", "Full rights to approved final artwork."],
        ],
        "use_cases" => ["New businesses needing first logo", "Product sub-brands within parent company", "Event and campaign-specific visual marks"],
        "technologies" => ["Illustrator", "Photoshop", "Figma", "Affinity Designer"],
    ],
    "design-systems" => [
        "lead" => "Unified design systems with components, tokens and documentation — ship features faster with consistency.",
        "overview" => "Design systems reduce inconsistency and speed up product teams. We audit existing UI, define tokens, build component libraries in Figma and sync with Storybook or code so designers and developers speak one language.",
        "features" => [
            ["UI Audit", "Inventory of patterns, gaps and inconsistencies."],
            ["Design Tokens", "Color, spacing, typography and elevation scales."],
            ["Component Library", "Buttons, forms, modals and data display patterns."],
            ["Documentation", "Usage guidelines and Storybook / Figma setup."],
        ],
        "benefits" => [
            ["Faster Shipping", "Reuse components instead of redesigning each screen."],
            ["Brand Consistency", "Same look across web, mobile and marketing."],
            ["Onboarding Speed", "New designers and devs ramp up quickly."],
            ["Accessibility Built-In", "Tested patterns meet WCAG baselines."],
        ],
        "use_cases" => ["Scale-ups with multiple product squads", "Rebrands needing systematic rollout", "Enterprises standardizing vendor deliverables"],
        "technologies" => ["Figma", "Storybook", "Tailwind", "Style Dictionary", "Chromatic"],
    ],
    "motion-graphics" => [
        "lead" => "Engaging motion graphics for explainers, social ads, UI animations and brand storytelling.",
        "overview" => "Motion captures attention and explains complex ideas quickly. We storyboard, animate and export for web, social and app contexts — including Lottie files for lightweight UI micro-animations.",
        "features" => [
            ["Storyboarding", "Scripts and frames aligned to message and brand."],
            ["2D Animation", "Character, icon and typography-driven motion."],
            ["Social Formats", "Square, vertical and short-form cuts for platforms."],
            ["UI Micro-Animations", "Lottie and CSS exports for product interfaces."],
        ],
        "benefits" => [
            ["Higher Engagement", "Motion posts outperform static on social."],
            ["Clear Communication", "Explain products in seconds, not paragraphs."],
            ["Premium Feel", "Polish that elevates perceived product quality."],
            ["Multi-Channel Reuse", "One asset adapted for ads, site and app."],
        ],
        "use_cases" => ["SaaS explainer videos for homepage hero", "Social ad creatives with motion hooks", "App onboarding and success animations"],
        "technologies" => ["After Effects", "Lottie", "Premiere Pro", "Cinema 4D", "Rive"],
    ],
    "product-design" => [
        "lead" => "End-to-end product design from discovery to developer handoff — UX strategy, UI and design sprints.",
        "overview" => "Product design spans the full lifecycle. We facilitate design sprints, validate ideas with prototypes and deliver specs developers can build without guesswork — keeping user needs and business goals aligned.",
        "features" => [
            ["Product Discovery", "Problem framing, opportunity mapping and prioritization."],
            ["Design Sprints", "Five-day cycles from challenge to tested prototype."],
            ["Interactive Prototypes", "Clickable flows for stakeholder and user testing."],
            ["Developer Handoff", "Annotated specs, assets and acceptance criteria."],
        ],
        "benefits" => [
            ["De-Risked Builds", "Validate before investing in full development."],
            ["User-Led Roadmap", "Features backed by research, not assumptions."],
            ["Cross-Functional Alignment", "Design, product and engineering on same page."],
            ["Faster Time to Value", "Clear specs reduce implementation delays."],
        ],
        "use_cases" => ["New product zero-to-one design", "Feature discovery for existing platforms", "Pivot validation with rapid prototyping"],
        "technologies" => ["Figma", "FigJam", "Maze", "Notion", "Jira"],
    ],
    "interactive-prototypes" => [
        "lead" => "Clickable prototypes for user testing, investor pitches and dev alignment — before writing production code.",
        "overview" => "Prototypes make ideas tangible. We build high-fidelity interactive flows in Figma or Framer, run test scripts with real users and iterate until the experience feels right — saving months of potential rework.",
        "features" => [
            ["Clickable Flows", "Multi-screen journeys with realistic interactions."],
            ["User Test Scripts", "Tasks, success metrics and recruitment guidance."],
            ["Iteration Rounds", "Incorporate feedback between test sessions."],
            ["Final Deliverables", "Figma/Framer files ready for development reference."],
        ],
        "benefits" => [
            ["Stakeholder Buy-In", "Show, do not tell — demos win approvals."],
            ["User Validation", "Find usability issues when fixes are cheap."],
            ["Dev Clarity", "Engineers build against approved interactions."],
            ["Investor Ready", "Polished demos for fundraising conversations."],
        ],
        "use_cases" => ["Pre-seed startups pitching with product demos", "Enterprise features needing sign-off before build", "Usability studies on checkout or onboarding"],
        "technologies" => ["Figma", "Framer", "ProtoPie", "Maze", "UserTesting"],
    ],
];
